Fix `read_timeliness_attribute_before_type_cast
adzap/validates_timeliness pull request #231
Opened 2023-03-10 15:13 UTC by TastyPi

`@attributes[attr_name]` returns an `ActiveModel::Attribute` not a value, this fixes that.

I'm not familiar enough with how the library works to write a test that hits this code path, all I know is in our codebase validation with `format` doesn't work without this change. All the current tests pass before and after this change, so I don't think any of the existing tests are hitting this code path.

2023-03-14 19:15 UTC, TastyPi commented
@adzap could this fix be merged please?

2023-03-16 11:49 UTC, tagliala commented
Is it possible to have a reproducible test case, so we can write a failing spec?

2023-03-16 12:49 UTC, tagliala requested changes

2023-03-16 12:49 UTC, tagliala commented on spec/spec_helper.rb
> +  c.use_plugin_parser = true
please do not set this at global level, I can see there is this helper:

```
    with_config(:use_plugin_parser, true)
```

2023-03-17 01:10 UTC, adzap commented
Thanks for getting a spec together @TastyPi . You are right this was untested and an undocumented and it needs both. 

There is an existing ActiveModel spec file completely empty here https://github.com/adzap/validates_timeliness/blob/master/spec/validates_timeliness/orm/active_model_spec.rb

Would you mind adapting your spec to work in there. Your spec seems to be focussed on the format option for some reason. Perhaps use the ActiveRecord ORM spec for guide on a minimal ORM spec https://github.com/adzap/validates_timeliness/blob/master/spec/validates_timeliness/orm/active_record_spec.rb. Though not all the specs for ActiveRecord are appropriate for ActiveModel.

2023-03-17 02:35 UTC, TastyPi commented
@adzap it's focused on the format option because that's the only option (afaict) that needs to get the "before type cast" value, and that's the only time this code path is hit.

I don't have the time right now to write tests covering the whole ORM, work is pretty busy and I've literally used this library for less than a week so I'm not familiar with all the ins and outs (I just needed a way to validate the format of some dates, and this looked like a good choice). I can maybe look at it in a month or two, but it would be nice to get the bug fix merged sooner. I can move the tests I've written into the ActiveModel spec file or anywhere else more appropriate, but I can't really commit to more than that I'm afraid.

2023-03-22 01:07 UTC, adzap commented
@TastyPi ok cool. I will merge this as the format spec is a missing spec for validator generally. Thanks.

2023-03-22 01:07 UTC, merged

2023-03-24 04:56 UTC, adzap commented
I've released a new beta with this change and some others to improve the ActiveModel testing and code. It was quite outdated and probably needs more work. Please give it a test @TastyPi